create table public.trips (
  trip_id text null,
  ordernumber text null,
  rate text null,
  status text not null default 'pending'::text,
  startdate date null,
  end_date date null,
  cost_centre text null,
  origin text null,
  destination text null,
  cargo text null,
  cargo_weight text null,
  notes text null,
  drivers jsonb null,
  vehicles jsonb null,
  vehicle_assignments jsonb null,
  pickup_locations jsonb null,
  dropoff_locations jsonb null,
  waypoints jsonb null,
  selected_stop_points jsonb null,
  stop_points jsonb null,
  selected_client text null,
  client_details jsonb null,
  status_notes text null,
  route text null,
  driver text null,
  vehicle text null,
  distance text null,
  costcentre jsonb null,
  enddate text null,
  cargoweight text null,
  vehicleassignments jsonb null default '[]'::jsonb,
  pickuplocations jsonb null default '[]'::jsonb,
  dropofflocations jsonb null default '[]'::jsonb,
  selectedstoppoints jsonb null default '[]'::jsonb,
  stoppoints jsonb null default '[]'::jsonb,
  selectedclient text null,
  clientdetails jsonb null default '{"name": "", "email": "", "phone": "", "address": "", "contactPerson": ""}'::jsonb,
  statusnotes text null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  id bigint generated always as identity not null,
  status_history text[] null,
  load_inspection_id bigint null,
  approximate_fuel_cost numeric(10, 2) null,
  approximated_cpk numeric(10, 4) null,
  approximated_vehicle_cost numeric(10, 2) null,
  approximated_driver_cost numeric(10, 2) null,
  total_vehicle_cost numeric(10, 2) null,
  goods_in_transit_premium numeric(10, 2) null,
  estimated_distance numeric(10, 2) null,
  fuel_price_per_liter numeric(10, 2) null,
  trip_type character varying(20) null default 'local'::character varying,
  current_latitude numeric(10, 8) null,
  current_longitude numeric(11, 8) null,
  current_speed numeric(5, 2) null default 0,
  last_location_update timestamp with time zone null,
  route_points jsonb null default '[]'::jsonb,
  unauthorized_stops_count integer null default 0,
  last_break_time timestamp with time zone null,
  break_reminder_due boolean null default false,
  driving_hours numeric(5, 2) null default 0,
  alert_message text null,
  alert_type text null,
  alert_timestamp timestamp with time zone null,
  accepted_at timestamp with time zone null,
  loading_location_lat numeric(10, 8) null,
  loading_location_lng numeric(11, 8) null,
  loading_location_radius numeric(5, 2) null default 100,
  late_acceptance boolean null default false,
  late_arrival boolean null default false,
  start_mileage numeric(10, 2) null,
  end_mileage numeric(10, 2) null,
  total_distance numeric(10, 2) null,
  constraint trips_pkey primary key (id),
  constraint trips_trip_id_key unique (trip_id),
  constraint trips_load_inspection_id_fkey foreign KEY (load_inspection_id) references load_inspections (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_trips_status_updated on public.trips using btree (status, updated_at) TABLESPACE pg_default
where
  (status <> 'completed'::text);

create index IF not exists idx_trips_alert_type on public.trips using btree (alert_type, alert_timestamp) TABLESPACE pg_default
where
  (alert_type is not null);

create index IF not exists idx_trips_location_update on public.trips using btree (last_location_update) TABLESPACE pg_default
where
  (last_location_update is not null);

create index IF not exists idx_trips_route_points on public.trips using gin (route_points) TABLESPACE pg_default;

create index IF not exists idx_trips_route_points_gin on public.trips using gin (route_points) TABLESPACE pg_default;

create index IF not exists idx_trips_vehicleassignments_gin on public.trips using gin (vehicleassignments) TABLESPACE pg_default;

create index IF not exists idx_trips_drivers_gin on public.trips using gin (drivers) TABLESPACE pg_default;

create index IF not exists idx_trips_vehicles_gin on public.trips using gin (vehicles) TABLESPACE pg_default;

create trigger audit_completed_trips
after
update on trips for EACH row
execute FUNCTION copy_completed_trip_to_audit ();





create table public.routes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  start_points text null,
  end_points text null,
  order_number text null,
  route_data jsonb null,
  vehicle_id text null,
  distance_km numeric null,
  duration_minutes integer null,
  estimated_eta timestamp with time zone null,
  truck_restrictions jsonb null,
  traffic_warnings jsonb null,
  route_geometry jsonb null,
  status text null default 'planned'::text,
  tollgates jsonb null,
  constraint routes_pkey primary key (id)
) TABLESPACE pg_default;


create table public.audit (
  trip_id text null,
  ordernumber text null,
  rate text null,
  status text not null default 'pending'::text,
  startdate date null,
  end_date date null,
  cost_centre text null,
  origin text null,
  destination text null,
  cargo text null,
  cargo_weight text null,
  notes text null,
  drivers jsonb null,
  vehicles jsonb null,
  vehicle_assignments jsonb null,
  pickup_locations jsonb null,
  dropoff_locations jsonb null,
  waypoints jsonb null,
  selected_stop_points jsonb null,
  stop_points jsonb null,
  selected_client text null,
  client_details jsonb null,
  status_notes text null,
  route text null,
  driver text null,
  vehicle text null,
  distance text null,
  costcentre jsonb null,
  enddate text null,
  cargoweight text null,
  vehicleassignments jsonb null default '[]'::jsonb,
  pickuplocations jsonb null default '[]'::jsonb,
  dropofflocations jsonb null default '[]'::jsonb,
  selectedstoppoints jsonb null default '[]'::jsonb,
  stoppoints jsonb null default '[]'::jsonb,
  selectedclient text null,
  clientdetails jsonb null default '{"name": "", "email": "", "phone": "", "address": "", "contactPerson": ""}'::jsonb,
  statusnotes text null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  id bigint generated always as identity not null,
  status_history text[] null,
  load_inspection_id bigint null,
  actual_start timestamp with time zone null,
  actual_end_time timestamp with time zone null,
  time_diff numeric null,
  constraint audit_pkey primary key (id),
  constraint audit_trip_id_key unique (trip_id),
  constraint audit_load_inspection_id_fkey foreign KEY (load_inspection_id) references load_inspections (id) on delete set null
) TABLESPACE pg_default;



create table public.clients (
  id bigint generated by default as identity not null,
  name text not null default ''::text,
  contact_person text null default ''::text,
  email text null default ''::text,
  phone text null default ''::text,
  address text null default ''::text,
  street text null default ''::text,
  city text null default ''::text,
  state text null default ''::text,
  country text null default ''::text,
  coords text null default ''::text,
  industry text null default ''::text,
  ck_number text null default ''::text,
  tax_number text null default ''::text,
  vat_number text null default ''::text,
  status text not null default 'Active'::text,
  client_id text null,
  pickup_locations jsonb null default '[]'::jsonb,
  dropoff_locations jsonb null default '[]'::jsonb,
  constraint clients_pkey primary key (id),
  constraint clients_id_key unique (id)
) TABLESPACE pg_default;


create table public.stop_points (
  id bigint generated always as identity not null,
  name text null,
  type text null default 'warehouse'::text,
  address text null,
  street text null,
  city text null,
  state text null,
  country text null,
  coords text null,
  coordinates text null,
  contact_person text null,
  contact_phone text null,
  contact_email text null,
  operating_hours text null,
  capacity text null,
  notes text null,
  facilities text[] null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint stop_points_pkey primary key (id)
) TABLESPACE pg_default;


create table public.job_assignments (
  accepted boolean null,
  result_images text[] null,
  completed_at timestamp without time zone null,
  id bigint generated by default as identity not null,
  location text null,
  emergency_type text null,
  description text not null,
  fleet_status text null,
  order_no text null,
  status text null default 'Breakdown Request'::text,
  priority text null default 'medium'::text,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  coordinates jsonb null,
  assigned_technician uuid null,
  technician_phone text null,
  estimated_cost numeric(10, 2) null,
  actual_cost numeric(10, 2) null,
  client_type text null,
  client_name text null default '''LP Truck Breakdown Brigade''::text'::text,
  approval_required boolean null default false,
  approved_by text null,
  approved_at timestamp with time zone null,
  notes text null,
  attachments text[] null default '{}'::text[],
  technician_id integer null,
  breakdowns_id bigint null,
  job_id text null,
  job_status text null default 'Onprogress'::text,
  created_by uuid null,
  updated_by uuid null,
  breakdown_req boolean null default false,
  inspected boolean null,
  image_path text null,
  scanned boolean null default false,
  driver_id bigint null,
  eta text null,
  vehicle_id bigint null,
  service text null,
  constraint job_assignments_pkey primary key (id),
  constraint job_assignments_job_id_key unique (job_id),
  constraint job_assignments_driver_id_fkey foreign KEY (driver_id) references drivers (id),
  constraint job_assignments_vehicle_id_fkey foreign KEY (vehicle_id) references vehiclesc (id),
  constraint job_assignments_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint job_assignments_technician_id_fkey foreign KEY (technician_id) references technicians (id),
  constraint job_assignments_status_check check (
    (
      status = any (
        array[
          'pending'::text,
          'assigned'::text,
          'inprogress'::text,
          'awaiting-approval'::text,
          'approved'::text,
          'completed'::text,
          'cancelled'::text,
          'Breakdown Request'::text,
          'Breakdown assigned'::text,
          'Technician accepted'::text,
          'Technician on site'::text,
          'Technician working'::text,
          'Tow requested'::text
        ]
      )
    )
  ),
  constraint job_assignments_client_type_check check (
    (
      client_type = any (array['internal'::text, 'external'::text])
    )
  ),
  constraint job_assignments_priority_check check (
    (
      priority = any (
        array[
          'low'::text,
          'medium'::text,
          'high'::text,
          'emergency'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;