-- ============================================================
-- Defects table migration
-- Run this in Supabase SQL Editor
-- ============================================================

-- 1. Create defects table
CREATE TABLE IF NOT EXISTS public.defects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Links
  inspection_id bigint REFERENCES public.inspections(id) ON DELETE SET NULL,
  workshop_job_id bigint REFERENCES public.workshop_job(id) ON DELETE SET NULL,
  vehicle_id bigint REFERENCES public.vehiclesc(id) ON DELETE SET NULL,
  driver_id bigint REFERENCES public.drivers(id) ON DELETE SET NULL,
  
  -- Defect details
  defect_name text NOT NULL,
  defect_category text,
  defect_description text,
  defect_status text NOT NULL DEFAULT 'Logged'::text,
  
  -- Tracking
  priority text DEFAULT 'medium'::text,
  notes text,
  
  -- Timestamps for each status
  logged_at timestamptz DEFAULT now(),
  reviewed_at timestamptz,
  approved_at timestamptz,
  assigned_at timestamptz,
  in_progress_at timestamptz,
  rectified_at timestamptz,
  rejected_at timestamptz,
  
  -- Metadata
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 2. Indexes
CREATE INDEX IF NOT EXISTS defects_inspection_id_idx ON public.defects USING btree (inspection_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS defects_workshop_job_id_idx ON public.defects USING btree (workshop_job_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS defects_status_idx ON public.defects USING btree (defect_status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS defects_vehicle_id_idx ON public.defects USING btree (vehicle_id) TABLESPACE pg_default;

-- 3. Enable RLS (Row Level Security) - match existing tables
ALTER TABLE public.defects ENABLE ROW LEVEL SECURITY;

-- 4. Allow all operations for authenticated users (match existing pattern)
CREATE POLICY "Allow all for authenticated" ON public.defects
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- 5. Allow all for anon (match existing pattern if needed)
CREATE POLICY "Allow all for anon" ON public.defects
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

-- 6. Create updated_at trigger function (if not exists)
CREATE OR REPLACE FUNCTION update_defects_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 7. Attach trigger to defects table
DROP TRIGGER IF EXISTS defects_updated_at_trigger ON public.defects;
CREATE TRIGGER defects_updated_at_trigger
  BEFORE UPDATE ON public.defects
  FOR EACH ROW
  EXECUTE FUNCTION update_defects_updated_at();

-- 8. Create function to sync defect status with workshop_job status
CREATE OR REPLACE FUNCTION sync_defect_status_from_job()
RETURNS TRIGGER AS $$
BEGIN
  -- When workshop_job status changes, update all linked defects
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    UPDATE public.defects
    SET defect_status = CASE
      WHEN NEW.status = 'Awaiting Approval' THEN 'Under Review'
      WHEN NEW.status = 'Approved' THEN 'Approved'
      WHEN NEW.status = 'In Progress' THEN 'In Progress'
      WHEN NEW.status = 'Completed' THEN 'Rectified'
      WHEN NEW.status = 'Rejected' THEN 'Rejected'
      ELSE defect_status
    END,
    reviewed_at = CASE WHEN NEW.status = 'Awaiting Approval' THEN now() ELSE reviewed_at END,
    approved_at = CASE WHEN NEW.status = 'Approved' THEN now() ELSE approved_at END,
    in_progress_at = CASE WHEN NEW.status = 'In Progress' THEN now() ELSE in_progress_at END,
    rectified_at = CASE WHEN NEW.status = 'Completed' THEN now() ELSE rectified_at END,
    rejected_at = CASE WHEN NEW.status = 'Rejected' THEN now() ELSE rejected_at END
    WHERE workshop_job_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 9. Attach trigger to workshop_job for status sync
DROP TRIGGER IF EXISTS workshop_job_status_sync_trigger ON public.workshop_job;
CREATE TRIGGER workshop_job_status_sync_trigger
  AFTER UPDATE OF status ON public.workshop_job
  FOR EACH ROW
  EXECUTE FUNCTION sync_defect_status_from_job();
